version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://mongo:27017/trip-planner
      - API_KEY=${API_KEY}
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
